"""
guardrails.py

SQL safety layer for the Claude agent. Any SQL string generated by
Claude must pass through validate_sql() before being executed against
Postgres. This ensures the agent can NEVER modify or destroy data,
regardless of what the user asks or how Claude interprets the request.

This is a real production AI engineering practice -- LLM-generated
code should never be trusted to execute without validation, especially
against a live database.
"""

import re

# These are the SQL keywords that would modify or destroy data.
# We block them unconditionally -- no exceptions, no overrides.
FORBIDDEN_KEYWORDS = [
    "DROP", "DELETE", "UPDATE", "INSERT", "ALTER",
    "TRUNCATE", "CREATE", "REPLACE", "GRANT", "REVOKE"
]

def validate_sql(sql: str) -> tuple[bool, str]:
    """
    Validates that a SQL string is safe to execute.

    Returns a tuple of (is_valid, reason):
      - (True, "OK") if the SQL is safe to run
      - (False, reason) if it's blocked, with a human-readable explanation

    Strategy: normalize the SQL to uppercase and strip comments first,
    then check that it starts with SELECT and contains no forbidden
    keywords. Both checks are required -- a clever prompt might try to
    embed a forbidden keyword inside a subquery or comment.
    """

    # Strip SQL comments (-- single line and /* multi-line */) before
    # checking, so someone can't hide a DROP inside a comment that
    # gets parsed differently by Postgres vs our regex.
    sql_no_comments = re.sub(r'--[^\n]*', '', sql)           # remove -- comments
    sql_no_comments = re.sub(r'/\*.*?\*/', '', sql_no_comments, flags=re.DOTALL)  # remove /* */ comments
    sql_upper = sql_no_comments.upper().strip()

    # Rule 1: must start with SELECT (after stripping whitespace).
    # This blocks any statement that isn't a read-only query.
    if not sql_upper.startswith("SELECT"):
        return False, f"Blocked: SQL must start with SELECT. Got: {sql_upper[:50]}..."

    # Rule 2: must not contain any forbidden keyword anywhere in the
    # statement -- even inside subqueries.
    for keyword in FORBIDDEN_KEYWORDS:
        # Use word boundaries (\b) so we don't accidentally block
        # a column named e.g. "created_at" because it contains "create".
        pattern = rf'\b{keyword}\b'
        if re.search(pattern, sql_upper):
            return False, f"Blocked: forbidden keyword '{keyword}' found in SQL."

    return True, "OK"


def safe_execute(cur, sql: str) -> tuple[bool, str, list]:
    """
    Validates and executes a SQL string against an open psycopg2 cursor.

    Returns (success, message, rows):
      - success: True if query ran cleanly, False otherwise
      - message: human-readable status or error description
      - rows: list of result rows (empty list if query failed)
    """
    is_valid, reason = validate_sql(sql)

    if not is_valid:
        # Log the blocked attempt and return immediately -- never execute.
        print(f"[GUARDRAIL BLOCKED] {reason}")
        return False, reason, []

    try:
        cur.execute(sql)
        rows = cur.fetchall()
        return True, "OK", rows
    except Exception as e:
        return False, f"SQL execution error: {str(e)}", []
